# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "sdkgenny"

[options]
SDKGENNY_BUILD_EXAMPLES = false

[conditions]
build-examples = "SDKGENNY_BUILD_EXAMPLES"

[vcpkg]
version = "2021.12.01"
packages = ["pegtl"]

[find-package]
pegtl = {}

[target.sdkgenny]
type = "interface"
include-directories = ["include/"]
compile-features = ["cxx_std_17"]
alias = "sdkgenny::sdkgenny"

[target.example_car]
condition = "build-examples"
type = "executable"
sources = ["examples/Car.cpp"]
link-libraries = ["sdkgenny"]

[target.example_bitfield]
condition = "build-examples"
type = "executable"
sources = ["examples/Bitfield.cpp"]
link-libraries = ["sdkgenny"]

[target.example_typename]
condition = "build-examples"
type = "executable"
sources = ["examples/Typename.cpp"]
link-libraries = ["sdkgenny"]

[target.example_usage]
condition = "build-examples"
type = "executable"
sources = ["examples/Usage.cpp"]
link-libraries = ["sdkgenny"]

[target.example_sdk]
condition = "build-examples"
type = "executable"
sources = ["examples/Sdk.cpp"]
link-libraries = ["sdkgenny"]

[target.example_dummydata]
condition = "build-examples"
type = "executable"
sources = ["examples/DummyData.cpp"]
link-libraries = ["sdkgenny"]

[target.example_badname]
condition = "build-examples"
type = "executable"
sources = ["examples/BadName.cpp"]
link-libraries = ["sdkgenny"]

[target.example_constants]
condition = "build-examples"
type = "executable"
sources = ["examples/Constants.cpp"]
link-libraries = ["sdkgenny"]

[target.example_parser]
condition = "build-examples"
type = "executable"
sources = ["examples/Parser.cpp"]
link-libraries = ["sdkgenny", "taocpp::pegtl"]
